[package]
name = "euler"
version = "0.1.0"
edition = "2018"

[dependencies]
ciborium = "0.1"
clap = "3.0.0-beta"
gridiron = { path = "../..", features = ["mpi"] }
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
